language: node_js

node_js:
  - '0.12'

compiler: clang

before_install:
  # Fix a problem with apt-get failing later, see http://docs.travis-ci.com/user/installing-dependencies/#Installing-Ubuntu-packages
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
  - sudo apt-get install --force-yes libcv-dev libcvaux-dev libhighgui-dev libopencv-dev libleptonica-dev libtesseract-dev libzbar-dev
  # put local node-pre-gyp on PATH
  - export PATH=./node_modules/.bin/:$PATH
  # install node-pre-gyp so it is available for packaging and publishing
  - npm install node-gyp -g
  # install node-pre-gyp so it is available for packaging and publishing
  - npm install node-pre-gyp

install:
  # ensure source install works
  - npm install --build-from-source
  # test our module
  - node lib/main.js

before_script:
  # cleanup
  - node-gyp clean
  - sudo apt-get purge libcv-dev
  - sudo apt-get purge libopencv-dev
  - sudo apt-get purge libhighgui-dev
  - sudo apt-get purge libleptonica-dev
  - sudo apt-get purge libtesseract-dev
  - sudo apt-get purge libzbar-dev

script:
  # If success then we arrive here so lets clean up
  - node-gyp clean

after_success:
  # if success then query and display all published binaries
  - node-gyp info
